// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgbdndherdtifodzhmiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnYmRuZGhlcmR0aWZvZHpobWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDQyMDQsImV4cCI6MjA3MTg4MDIwNH0.xYeGILbBsvEUPLoX1AsVx713KVt-b34B6F-sagtYBhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});